### ISSUE TITLE
Add /sitemap.atom feed

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1014]
This let's google know what's the newest stuff on the site without having to regenerate the xml sitemap every time something new is added, details here: https://webmasters.googleblog.com/2014/10/best-practices-for-xml-sitemaps-rssatom.html

Things to include:

- [ ] New and recently updated projects
- [ ] New and recently updated github repositories
- [ ] New and recently updated github orgs
- [ ] New and recently updated github users

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
