### ISSUE TITLE
Improve test coverage of Package Manager classes

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1048]
- [ ] alcatraz.rb
- [ ] atom.rb
- [ ] base.rb
- [ ] bower.rb
- [ ] cargo.rb
- [ ] carthage.rb
- [ ] clojars.rb
- [ ] cocoa_pods.rb
- [ ] cpan.rb
- [ ] cran.rb
- [ ] dub.rb
- [ ] elm.rb
- [ ] emacs.rb
- [ ] go.rb
- [ ] hackage.rb
- [ ] haxelib.rb
- [ ] hex.rb
- [ ] homebrew.rb
- [ ] inqlude.rb
- [ ] julia.rb
- [ ] maven.rb
- [ ] meteor.rb
- [ ] nimble.rb
- [ ] npm.rb
- [ ] nu_get.rb
- [ ] packagist.rb
- [ ] platform_io.rb
- [ ] pub.rb
- [ ] pypi.rb
- [ ] rubygems.rb
- [ ] shards.rb
- [ ] sublime.rb
- [ ] swift_pm.rb
- [ ] wordpress.rb

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
