### ISSUE TITLE
Open Data Ship List

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1483]
Todo list issue for #609 and https://github.com/librariesio/supporters/issues/9

- [x] Decide on fields 
- [x] Export tasks
- [x] Setup open data mailing list in mailchimp
- [x] Documentation #1485
- [x] Create `https://libraries.io/open-data` as homepage for the release #1485
- [x] Data cleanup https://github.com/librariesio/libraries.io/issues/1483#issuecomment-307336775
- [x] Add primary keys to projects, versions and repository csvs
- [x] Test importing of all csvs to big query
- [x] Collect quotes for promotion
- [x] Make list of people to reach out to about launch
- [x] Press release and announcement blog post
- [x] Initial Export and upload to s3
- [x] Get DOI numbers
- [x] Decide on upload locations and mirrors
- [ ] Add to https://github.com/caesar0301/awesome-public-datasets

Related but not required:

- Improve API documentation
- Add list of API clients
- Add license information to footer of the site
- Add license information to API with commercial prompt to contact `support@libraries.io`

**Comment by andrew** [comment]
Tables to be exported:

- Dependencies
- Manifests
- Projects
- Repository Dependencies
- Repository
- Tag
- Version

Tables we won't be exporting as the data is available elsewhere in more reliable forms:

- Issues
- Readmes

We won't be exporting any User related data in this first release, namely these tables:

- Contribution
- Repository Users
- Repository Organisations

**Comment by BenJam** [comment]
The DOI number thing seems like it would be managed by Zenodo no? worth a check, otherwise CrossRef has the nicest logo of any doi provider 😬

**Comment by andrew** [comment]
First version of the export rake tasks are now merged: https://github.com/librariesio/libraries.io/blob/master/lib/tasks/open_data.rake

**Comment by andrew** [comment]
Some initial stats:

- projects
  - filesize: 649MB
  - compressed: 147MB
  - rows: 2,607,879
- versions
  - filesize: 932M
  - compressed: 136M
  - rows: 9,244,443
- dependencies
  - filesize: 228M
  - compressed: 147MB
  - rows: 49,826,914

**Comment by andrew** [comment]
Currently investigating some invalid rows being generated in the projects csv file

**Comment by andrew** [comment]
A folder containing all 6 csv files gzipped comes in at 4.3GB

**Comment by andrew** [comment]
Plans for data cleanup:

- [ ] check all projects to see if they've been yanked/removed
- [ ] resync as many projects as possible
- [ ] check repositories with at least one dependency to see if they've been removed
- [ ] resync most popular repositories

**Comment by andrew** [comment]
Thinking about adding back in the primary keys for projects, versions and repositories to make joining the data in the different csv files.

**Comment by BenJam** [comment]
I've created data@ and opendata@ btw.

**Comment by andrew** [comment]
Submitted pr to awesome-public-datasets: https://github.com/caesar0301/awesome-public-datasets/pull/300

**Comment by andrew** [comment]
🚢
