### ISSUE TITLE
Repository Monitoring settings page

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#160]
Move the current /dashboard UI into a separate page for configuring which repositories should be monitored by Libraries, more like a settings interface than a homepage.
- [x] Show [`last_synced_at`](https://github.com/librariesio/libraries/issues/169), sync status and sync button
- [ ] Ajax toggle watch button
- [x] Slimline GitHub repo partial
- [x] Show current selected org 
- [ ] Sorting options for repositories
- [ ] Search repos
- [ ] Show repository count for orgs
- [ ] Show repos you don't have webhook access as disabled
- [x] Link to manage org access, similar to travis `https://github.com/settings/connections/applications/#{GITHUB_KEY}`
- [ ] Expand to see dependencies

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
