### ISSUE TITLE
Mute individual projects

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#162]
If you're monitoring a repository, you should be able to mute notifications from any particular project that it depends on, say if you're not interested in hearing about notifications for that one library.
- [x] Mute link on project page
- [x] Mute link within the interface of repositories you're montioring
- [ ] Mute in search results (with option to show muted results)
