### ISSUE TITLE
Mark a user as "being synced"

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#169]
Whenever we start downloading repos and permissions for a user they should be marked as "syncing" and a spinner shown on the [Repository monitoring settings](https://github.com/librariesio/libraries/issues/160) page, which can then be hidden once it's done, with a timestamp of last sync time, update to the active page to be done with pusher.
- [x] add new User field `currently_syncing` boolean
- [x] add new User field `last_synced_at` datetime
- [x] toggle `currently_syncing` in `#update_repo_permissions_async`
- [x] update `last_synced_at` after `#update_repo_permissions_async` finishes
- [x] show spinner on [`/dashboard`](https://github.com/librariesio/libraries/issues/160) if `currently_syncing` is true otherwise show `last_synced_at`
- [x] sync users every 24 hours
- [x] "Sync now" button on [`/dashboard`](https://github.com/librariesio/libraries/issues/160)
- [ ] use `message_bus` to update  [`/dashboard`](https://github.com/librariesio/libraries/issues/160) when `#update_repo_permissions_async` is complete

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
