### ISSUE TITLE
Libraries.io 'facelift' redesign 

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#2059]
Libraries.io has a new home as part of Tidelift, and while it is a separate entity and project it should carry at least a sense of association through the look and feel. Including:

- [x] new libraries.io logo #2060 
- [ ] redesign of the home page to focus on search over the (many) elements there now #2061 
- [ ] marketing 'assets' for inclusion in Tidelift and third party usage/apps #2062 
- [ ] new UI components featuring a more tidelift-ish palette (this issue)

**Comment by andrew** [comment]
probably a good time to revisit https://github.com/librariesio/assets as well

**Comment by BenJam** [comment]
Yup 👍

**Comment by BenJam** [comment]
As part of this we may wish to move toward a flexbox-compatible CSS library like bootstrap 4. Requirement is still that the bar is set low for contributors. i.e. it should be simple and familiar for others to contribute features to the frontend without having to read through a design standards document.

**Comment by laurenhanford** [comment]
Here is some in-progress visual exploration for the Libraries facelift..

![libraries-moodboard_d01](https://user-images.githubusercontent.com/35534927/38639151-61ae0c46-3d9e-11e8-928f-0eba45eea4cd.jpg)

**Comment by laurenhanford** [comment]
as noted in slack, we'll need to revise the footer to be less **heavy**

**Comment by andrew** [comment]
@laurenhanford these are looking great, any thoughts on how the homepage graphics transforms on smaller screens?

**Comment by andrew** [comment]
I was thinking about the Explore sections the other day, aside from the terrible performance, feels like "Trending" could be redesigned to be a bit more of something you'd want to come back and check on a daily basis to find new, interesting things

**Comment by laurenhanford** [comment]
@andrew What factors determine when a package is trending?

**Comment by amyeastment** [comment]
Here are some in-progress designs for the redesign of the package/project pages. Goals include sorting information in a way that's easier to parse/find based on different priorities of libraries.io users, updating the look and feel per @laurenhanford 's sweet designs, and adding more context to the new SourceRank rating (these designs include a proposed presentation for the scoring + score breakdown). 

![libraries io package and score design v2 001](https://user-images.githubusercontent.com/896755/39891496-c11fc636-546b-11e8-81da-6d121853ef39.png)

![libraries io package and score design v2 002](https://user-images.githubusercontent.com/896755/39891501-c37a6a58-546b-11e8-9a70-b9eccc473aea.png)

![libraries io package and score design v2 003](https://user-images.githubusercontent.com/896755/39891528-d1c43da0-546b-11e8-9a99-ebd68467b8d5.png)

![libraries io package and score design v2 004](https://user-images.githubusercontent.com/896755/39891533-d735cf2e-546b-11e8-8dcb-b18031af79ad.png)

![libraries io package and score design v2 005](https://user-images.githubusercontent.com/896755/39891546-dd7e630a-546b-11e8-926b-6738e0ed4446.png)

![libraries io package and score design v2 006](https://user-images.githubusercontent.com/896755/39891555-e2bc71ea-546b-11e8-9bcc-dde72de37f0d.png)

Next up: 
- Search results
- A bit more "dig deeper" type of context for SourceRank 2.0 scoring

**Comment by andrew** [comment]
@laurenhanford I've been pondering the mobile version of the homepage you posted here, and I think it feels a bit long, and on reflection so does the current mobile homepage, I think we can strip it down to be a better launching off point of the key functions, perhaps as a set of icons or menu under the search box?

**Comment by laurenhanford** [comment]
@andrew ok, interesting.. I agree it is long — 

I wanted to keep the package manager directory visible and in a similar place because of click frequency from GA, and wanted to explain Libraries/Tidelift a bit more (although this could certainly be abbreviated, and not on the home page?) 

let's use our work session next week to talk about the user goals and how we might better surface key functions to support those goals more readily..

**Comment by katzj** [comment]
Closing this out for now
