### ISSUE TITLE
Paid plan improvements

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#207]
- [x] Pricing page should be publically available without logging in
- [x] Customize the stripe checkout form - https://github.com/peterkeen/payola/blob/master/app/views/payola/subscriptions/_checkout.html.erb
- [x] Bigger custom plans for big spenders + promo on pricing page
- [ ] handle all relevant webhooks [from stripe](https://www.masteringmodernpayments.com/stripe-webhook-event-cheatsheet#8)
- [ ] Upgrade plan
- [ ] Downgrade plan (make sure excess private repos are unwatched)
- [ ] Cancel plan (make sure private repos are unwatched)
- [ ] Hidden free private account for friends
- [ ] Better VAT handling (VATMOSS etc) - https://github.com/peterkeen/payola/issues/103#issuecomment-118010638

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
