### ISSUE TITLE
Keyword improvements

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#445]
- [ ] Lower case all keywords
- [ ] Deduplicate keywords on a project
- [ ] Truncate display of long keywords

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
