### ISSUE TITLE
Add more (package manager) registries

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#48]
### Supported
- [x] Hex
  - [x] include dependencies
- [x] Dub
  - [x] include dependencies
- [x] NPM
  - [x] include dependencies
- [x] Packagist
  - [x] include dependencies
- [x] Cargo
  - [x] include dependencies
- [x] Rubygems
  - [x] include dependencies
- [x] CRAN http://cran.r-project.org/web/packages/available_packages_by_name.html
  - [x] include dependencies
- [x] Elm http://package.elm-lang.org/packages
  - [x] include dependencies
- [x] CPAN http://www.cpan.org/modules/01modules.index.html https://github.com/CPAN-API/cpan-api
  - [x] include dependencies
- [x] Atom https://atom.io/packages/list
  - [x] include dependencies
- [x] Nuget
  - [x] include dependencies
- [x] Maven
  - [ ] include dependencies
- [x] Wordpress http://codex.wordpress.org/WordPress.org_API
  - [ ] include dependencies
- [x] Go http://go-search.org/api?action=packages
  - [ ] include dependencies
- [x] Meteor https://atmospherejs.com/packages/recent
  - [ ] include dependencies
- [x] Clojure https://github.com/ato/clojars-web/wiki/Data
  - [ ] include dependencies
- [x] Cocoapods https://github.com/CocoaPods/Specs/tree/master/Specs
  - [ ] include dependencies
- [x] Julia https://github.com/JuliaLang/METADATA.jl
  - [ ] include dependencies
- [x] Homebrew http://brewformulas.org/
  - [ ] include dependencies
- [x] Nimble
  - [ ] include dependencies
- [x] PyPi
  - [ ] include dependencies
- [x] Bower
  - [ ] include dependencies
- [x] Hackage
  - [ ] include dependencies

### Unsupported
- [ ] CTAN http://www.ctan.org/pkg
  - [ ] include dependencies
- [ ] Vim http://www.vim.org/scripts/script_search_results.php?order_by=creation_date&direction=descending
  - [ ] include dependencies
- [ ] Smalltalk http://smalltalkhub.com/
  - [ ] include dependencies
- [ ] Opam https://github.com/ocaml/opam-repository
  - [ ] include dependencies
- [ ] Lua rocks http://rocks.moonscript.org/manifest
  - [ ] include dependencies
- [ ] Pascal http://wiki.freepascal.org/fppkg
  - [ ] include dependencies
- [ ] Common Lisp http://www.quicklisp.org/beta/releases.html
  - [ ] include dependencies
- [ ] Erlang rebar https://github.com/rebar/rebar
  - [ ] include dependencies
- [ ] C https://github.com/clibs/clib/wiki/Packages
  - [ ] include dependencies
- [ ] Bash http://www.bpkg.io/packages/name/ http://modulereg.vertx.io/
  - [ ] include dependencies
- [ ] Puppet https://forge.puppetlabs.com/modules?utf-8=%E2%9C%93
  - [ ] include dependencies
- [ ] Ansible https://galaxy.ansible.com/
  -  [ ] include dependencies
- [ ] Chef https://supermarket.chef.io/
  - [ ] include dependencies
- [ ] Nix http://nixos.org/nixpkgs/
  - [ ] include dependencies
- [ ] Titanium http://gitt.io/
  - [ ] include dependencies
- [ ] Phonegap http://plugreg.com/
  - [ ] include dependencies
- [ ] Conda https://github.com/conda/conda-recipes
  - [ ] include dependencies
- [ ] Erlang https://github.com/ninenines/erlang.mk/blob/master/packages.v2.tsv
  - [ ] include dependencies
- [ ] Emacs, gnu default db, [marmalade](https://marmalade-repo.org/), [melpa](http://melpa.org/#/)
  - [ ] include dependencies

**Comment by andrew** [comment]
Needs breaking into separate smaller issues

**Comment by andrew** [comment]
@petems yeah please do open an issue for specific ones 👍

**Comment by BenJam** [comment]
We are in the process of adding specific guidance for contributors looking to add support for their favourite package manager or 'registry' in general. See librariesio/documentation#9

**Comment by andrew** [comment]
Dependency manifest files to potentially support (from https://github.com/librariesio/librarian/issues/5):

Maven/Java:
- [x] pom.xml
- [x] ivy.xml
- [ ] *.gradle
- [ ] build.sbt

Rubygems:
- [x] Gemfile.lock
- [x] example.gemspec

Pypi:
- [x] requirements.txt
- [x] setup.py
- [x] req*.txt
- [x] req*.pip
- [x] requirements/*.txt
- [x] requirements/*.pip
- [ ] buildout.cfg and versions.cfg,
- [ ] tox.ini

Packagist:
- [x] composer.lock ([json](https://github.com/librariesio/librarian/pull/39))

Cocoapods:
- [x] Podfile
- [x] Podfile.lock ([yaml](http://stackoverflow.com/questions/25875474/ruby-parse-dependencies-data-from-podfile-lock))
- [x] *.podspec https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking.podspec

Clojars
- [x] project.clj ([clojure map](https://github.com/librariesio/clojars-json/blob/master/project.clj))

Hex/Elixir:
- [x] mix.exs
- [x] mix.lock ([elixir map?](https://github.com/librariesio/mix-deps-json/blob/master/mix.lock))

D/Dub:
- [x] dub.json

Nim/Nimble:
- [ ] example.nimble ([init/toml?](https://github.com/vic/nim-heroku-example/blob/master/example.nimble))

Rust/Cargo:
- [x] Cargo.toml
- [x] [Cargo.lock](https://github.com/rust-lang/rust-by-example/blob/master/Cargo.lock) (also toml)

Meteor:
- [x] versions.json ([json](https://github.com/percolatestudio/meteor-intercom/blob/master/versions.json))
- [ ] package.js ([js](https://github.com/twbs/bootstrap/blob/master/package.js)

Haskell/Hackage:
- [ ] [example.cabal](https://github.com/chrisdone/yesod-fay-example/blob/master/example.cabal)

Dart/Pub:
- [x] pubspec.yaml
- [x] pubspec.lock ([yaml?](https://github.com/angular/angular.dart/blob/master/pubspec.lock))

Lua:
- [ ] example.rockspec [lua?](https://github.com/brimworks/lua-zlib/blob/master/rockspec)

Elm:
- [x] elm-stuff/exact-dependencies.json

Carthage:
- [x] [Cartfile](https://github.com/Carthage/Carthage/blob/master/Cartfile)
- [x] [Cartfile.private](https://github.com/Carthage/Carthage/blob/master/Cartfile.private)
- [x] [Cartfile.resolved](https://github.com/Carthage/Carthage/blob/master/Cartfile.resolved)

Julia
- [x] [REQUIRE](https://github.com/dcjones/Gadfly.jl/blob/master/REQUIRE)

PlatformIO
- [ ] [platformio.ini](https://raw.githubusercontent.com/zzolo/signal/master/platformio.ini)  ([docs](http://docs.platformio.org/en/latest/projectconf.html))

Nuget
- [x] [Packages.config](http://docs.nuget.org/Consume/ProjectJson-Intro)
- [x] [Project.json](http://docs.nuget.org/Consume/ProjectJson-Format)
- [x] [Project.lock.json](http://docs.nuget.org/Consume/ProjectJson-Format)
- [x] [example.nuspec](http://docs.nuget.org/Create/NuSpec-Reference)

CRAN
- [x] [DESCRIPTION](https://github.com/hadley/httr/blob/master/DESCRIPTION)
- [ ] [packages.R](https://github.com/siemens/codeface/blob/master/packages.R)?

CPAN
- [ ] [cpanfile](https://github.com/kraih/mojo/wiki/Installation-of-cpan-modules-by-cpanm-and-cpanfile)
- [x] META.json
- [x] META.yml
- [ ] dist.ini

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
