### ISSUE TITLE
Upgrade elasticsearch

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#581]
Currently using elasticsearch 1.7, the main blocker to updating is that facets have been replaced with aggregations.

Sub tasks:

- [x] Rename indexes to include environment name https://github.com/librariesio/libraries.io/pull/1273
- [x] Replace facets with aggregations https://github.com/librariesio/libraries.io/pull/1273
- [x] Move Cron from heroku to scaleway https://github.com/librariesio/infrastructure/issues/5
- [x] Log rotate in ES ansible playbook https://github.com/librariesio/infrastructure/issues/4
- [x] New elasticsearch cluster https://github.com/librariesio/infrastructure/issues/3

---

Deployment checklist:

- [x] Bring up new cluster
- [x] Merge https://github.com/librariesio/libraries.io/pull/1273
- [x] Update cron machine with new ES cluster config
- [x] Deploy librariesio/libraries.io to cron machine
- [x] Disable sidekiq workers
- [x] Index projects, repos and issues into new cluster
- [x] Update all servers with new ES config
- [x] Deploy librariesio/libraries.io to all servers
- [x] Renable sidekiq workers
- [x] Move amsterdam worker machines to paris

**Comment by andrew** [comment]
🚢
