### ISSUE TITLE
Cache dependent repo count onto projects

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#912]
Calculating the dependent repo count is pretty intensive, caching it into a column will speed things up and allow some more sorting options in sql 

- [x] New column https://github.com/librariesio/libraries.io/issues/914
- [x] Update data in column #916
- [x] Start using column #917
- [x] Index `dependent_repos_count` into elasticsearch #918
