### ISSUE TITLE
Merge support repo into main issue tracker

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#964]
https://github.com/librariesio/support was made for tracking public issues when the main repo was private, now it's open we should:
- [ ] transfer all the issues over
- [ ] update all links on the site to point to the main issue tracker
- [ ] disable issues on the support repo
- [ ] update the readme in the support repo to tell people to open issues on the main repo

**Comment by andrew** [comment]
I've made the support repo private for now so we don't lose the existing issues but won't get any more over there, there are no links to that repo in the main app so going to close this now.
